name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature!
        Please fill out the sections below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the user need?
      placeholder: "Example: As a developer, I need to auto-merge dependabot PRs, but gpm doesn't support this workflow"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "Example: Add `gpm auto-merge --dependabot` command that merges PRs with passing CI"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: "Example: I could use GitHub Actions auto-merge, but that requires workflow configuration"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my workflow)
        - High (Would significantly improve my workflow)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: dropdown
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, I can help with testing"
        - "Yes, I can help with documentation"
        - "No, but I can provide feedback"
        - "No contribution"
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be helpful
      placeholder: |
        1. When maintaining multiple repos, auto-merge patch updates to save time
        2. When working solo, reduce manual PR merging overhead
        3. When ensuring security updates are applied promptly
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: Who would benefit from this feature? How many users?
      placeholder: "Example: Solo developers and small teams managing multiple repositories"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: "Example: Similar to Renovate's auto-merge feature or Dependabot's auto-merge option"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues and PRs to ensure this isn't a duplicate
          required: true
        - label: I have clearly described the problem this feature solves
          required: true
